sudo: false
language: ruby
branches:
  only:
    - master
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-1.7.22
  - jruby-9.0.4.0
  - jruby-head
  - rbx-2.5.8
matrix:
  allow_failures:
      - rvm: ruby-head
      - rvm: jruby-head
after_success:
  - export CODECLIMATE_REPO_TOKEN=9b56bc5e14a34f1925548f4e0c61b9afe6b6d6da6227738218c4a99c88c10c65
  - bundle exec codeclimate-test-reporter
